version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0

  pre_build:
    commands:
      - echo ${CODEBUILD_SRC_DIR}
      - dotnet restore ./src/WebAPI.csproj

  build:
    commands:
      - echo Build started on `date`
      - dotnet build -c Release .src/WebAPI.csproj

  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release .src/WebAPI.csproj

artifacts:
  files:
    - "**/*"
