version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0

  pre_build:
    commands:
      - echo ${CODEBUILD_SRC_DIR}
      - dotnet restore ./src/WebAPI.csproj

  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -o ./publish_output -c Release  ./src/WebAPI.csproj --self-contained

artifacts:
  files:
    - "**/*"
  base-directory: ./publish_output
  discard-paths: no
