version: 0.1

env:
variables:
PROJECT: lsdkdl

phases:
  install:
    runtime-versions:
      dotnet: 6.0

pre_build:
  commands:
    - echo Restore started on `date`
    - dotnet restore

build:
  commands:
    - echo Build started on `date`
    - dotnet build -c Release

post_build:
  commands:
    - echo Publish started on `date`
    - dotnet publish -c Release -o ./publish

artifacts:
  files:
    - "**/*"
